name: ServerStuff
version: '${project.version}'
main: me.nik.serverstuff.ServerStuff
load: STARTUP
authors: [nik9094]
description: Background server things
commands:
    getreal:
        usage: /getreal
        description: Use this to get started (enables things)
    hub:
        usage: /hub
        description: Just... brings you to main hub

permissions:
    getreal.use:
        description: allows getreal command
    hub.use:
        description: allows hub command
